export const CONNECTION = "connection";
export const JOIN = "join";
export const MESSAGE = "message";
export const ROOMSTATUS = "roomData";
export const SENDMESSAGE = "sendMessage";
export const TYPING = "typing";
export const TYPINGSTATUS = "userTyping";
export const DISCONNECT = "disconnect";
export const ADMIN = "chat master";
